#-----------------------------------------------------------------------------
# File:    Makefile.srcs
#
# Author:  Ian Buckley, Ion Concepts LLC
#
# Description: Synthesizable System Verilog Source Code For Makefile Driven Flows
#
# License: CERN-OHL-P (See LICENSE.md)
#
#-----------------------------------------------------------------------------

DIRT_SPI_SRCS = $(abspath $(addprefix $(DIRT_DIR)/lib/spi/, \
axis_rtspi_pkg.sv \
axis_rtspi.sv \
spi.sv \
))
