#-----------------------------------------------------------------------------
# File:    Makefile.srcs
#
# Author:  Ian Buckley, Ion Concepts LLC
#
# Description: Synthesizable System Verilog Source Code For Makefile Driven Flows
#
# License: CERN-OHL-P (See LICENSE.md)
#
#-----------------------------------------------------------------------------

DIRT_IO_SRCS = $(abspath $(addprefix $(DIRT_DIR)/lib/io/, \
dirt_iobuf.sv \
dirt_ibufds.sv \
dirt_obufds.sv \
))
